### ISSUE TITLE
Indexing freeze with message: Indexing paused due to batch updated

### ISSUE THREAD

**Issue by fazalBykea** [spiir/nag-example-apps#4] opened 2018-11-13 04:27 UTC
I've updated Android Studio to version 3.2.

After that update one of my projects don't want to index.

It freezes with the message

`Indexing paused due to batch updated`

**Comment by bvdspiir** [comment] 2018-11-13 07:38
Have you tried to invalidate the cache in Android Studio? Check out if some of the solutions found in this thread will solve your issue: https://stackoverflow.com/questions/52513097/indexing-freeze-with-message-indexing-paused-due-to-batch-updated

If this does not do the trick, let me know, and I will look to see if it has anything to do with the project settings.

What OS are you using? MacOS, Windows or some Linux distribution?

**Comment by fazalBykea** [comment] 2018-11-15 05:21
Thanks for your answer. I have already explore the link but I have not found any solution suitable for my case. I am using Windows 10 OS. I have pressed the tiny play button which help me but its a work around not a permanent solutions. I have uninstalled Android Studio and install again but the problem still exist.

**Comment by bvdspiir** [comment] 2018-11-15 13:41
Let me get this right: You are saying that you can the project by pressing the tiny green play button? If that is the case, then everything is as it should be. Currently we do not provide any other ways of building or running this project than what is already available in a standard configured Android application.

**Comment by SaadBilal** [comment] 2019-01-05 15:14
Re-import the project is the only solution for me after trying all other solutions

**Comment by Nik-CS** [comment] 2019-03-11 08:42
This problem still exists, I still have it. And when @fazalBykea referenced the tiny play icon, it's the one that appears in the "Background Tasks" pop-up if you expand "2 processes running" next to the task `Indexing paused due to batch update` which skips that step I assume

**Comment by bvdspiir** [comment] 2019-03-12 09:32
Hi @Nik-CS 

Thank you for letting us know that this is still a problem for some of our users.

I am not able to reproduce the problem. It would help me if you could tell me what version of Android Studio you are using.

**Comment by mvettosi** [comment] 2019-03-19 13:17
I'm on Android Studio 3.3 and I too experience the problem every now and then

**Comment by Joseph82** [comment] 2019-03-19 15:31
I am on Android Studio 3.3 and I have the same problem. Invalidating cache and restart doesn't fix it. Other colleagues had the same problem just today.

**Comment by aznj** [comment] 2019-03-20 03:00
This issue seems to happened to a lot of other people including me.

**Comment by NoelOmo** [comment] 2019-03-23 09:50
Experienced the same issue after cloning a new project to my comp

**Comment by deepakbansal168** [comment] 2019-03-27 09:45
Experienced the same issue after cloning a new project to my comp

**Comment by jayj** [comment] 2019-03-27 09:49
It's a Android Studio bug. Here's the issue tracker: https://issuetracker.google.com/issues/118523471

**Comment by BugsCreator** [comment] 2019-04-18 02:36
Just do this:
File>Invalidate caches / Restart>Invalidate and restart.

It worked for me, I hope it should work for you guys too!

**Comment by samiul-basir** [comment] 2019-04-25 05:10
Thanks 
It worked for me

**Comment by Edgar-Spiir** [comment] 2019-04-25 08:00
Seems like the issue is resolved by invalidating caches, so I'm closing this for now.

**Closed by Edgar-Spiir** 2019-04-25 08:00 UTC
